### ISSUE TITLE
Add "Enter VR" button to extension chrome UI

### ISSUE THREAD

**Issue by cvan** [MozVR/webvr-addon#10]
**Depends on issue #9.**

<hr>

Aesthetics are flexible but here's a screenshot of a similar possible implementation:

![](https://cloud.githubusercontent.com/assets/203725/9344135/4aae9ae8-45bb-11e5-852b-5dd36ab54257.png)

Possibly show the "Enter VR" button only after the doorhanger is clicked. Although two clicks are unfortunate, it could be awkward to have the icon itself automatically enter VR mode because then the icon can't be reused for like activity state or something idk. Use your judgement.

**Comment by jcarpenter** [comment]
Related mockup from Presentation API discussion: 
![presentationapi-multiscreenusecases](https://cloud.githubusercontent.com/assets/1425497/9344872/c068c164-45c0-11e5-9b81-02d9d62ff3ce.png)
