### ISSUE TITLE
Use best setting as of today

### ISSUE THREAD

**Issue by caseyyee** [MozVR/webvr-addon#30]
e10s off
dom.vr.enabled = true
dom.vr.poseprediction.enabled = false
layout.frame_rate = 75
layout.frame_rate.precise = true
gfx.vr.mirror-textures = false

Windows 10,
Oculus 0.8 runtime

**Comment by cvan** [comment]
after GDC, do y'all (@caseyyee and @kearwood) agree these are the best pref settings?
