### ISSUE TITLE
Support for DK1? Rotating display prefs 90 degrees doesn't work.

### ISSUE THREAD

**Issue by odbol** [MozVR/webvr-addon#4]
Hi, I have a DK1, and the instructions on the website did not work for me on OS X 10.10. I matched my display settings to the readme: optimized for Rift, 90 degree rotation, mirrored. But the demos on the webvr site still displayed the images next to each other, so they stacked vertically in the headset display. 

When I turned rotation off, it was oriented correctly, however the scenes were not at the right size so it didn't look 3d, just like two images overlapping each other. Do I need to update my firmware or my Oculus SDK or something?

**Comment by cvan** [comment]
This probably isn't an issue anymore. And if it is, let's not fix it because the consumer version of the Oculus Rift has shipped :tada:
