### ISSUE TITLE
Can't install the extension

### ISSUE THREAD

**Issue by edouardlanctot** [MozVR/webvr-addon#5]
Firefox Nightly now refuses to install the extension at http://mozvr.com/downloads/ because it's unverified. Since version 42, Firefox doesn't allow unsigned extensions to be installed and there are no override.
See: https://wiki.mozilla.org/Addons/Extension_Signing

**Comment by nickdesaulniers** [comment]
Working on this now.

**Comment by nickdesaulniers** [comment]
@edouardlanctot please try: https://addons.mozilla.org/en-US/firefox/addon/mozilla-webvr-enabler/

**Comment by edouardlanctot** [comment]
@nickdesaulniers Thanks! Solved.
